In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris
import numpy as np

### 교차검등 kf, skf 외에  검증 추가할 예정 
- cross_val_score, cross_validate 
- 교차검증 가장 많이 사용하는 방법
- 기능적으로 좋은 부분이 
- 자체적으로 데이터 타입이 회귀 또는 분류에 따라서 kf ,skf 바꿔서 작업을 해준다.
- 데이터의 불균형이나 이런 것들 또는 타입에 따른 데이터 검증 방법을 생각할 필요 없이 
- 얘만 사용하면 편하게 가능하다!

- cross_val_score(사용할 모델, x값, Y값, scoring( 평가할 스코어링 방법 ) , cv 몇번 교차 검증할 것인가?, n_jobs( cpu사용에 대한 지정 -1)
, verbose (진행상황보기) 교차검증 되는 상황 체크 , fit_params 등등 )

In [2]:
iris_data = load_iris()

data= iris_data.data
label= iris_data.target

In [3]:
dt_clf = DecisionTreeClassifier(random_state=111)

In [4]:
#교차검증 진행
scores = cross_val_score(dt_clf, data, label, scoring='accuracy',cv=5)
print(np.round(np.mean(scores),3))

0.96


In [ ]:
# cross validate
# 소요시간, train, test에 대한 내가 원하는 지표를 다 볼 수 있다.

In [5]:
crs=cross_validate(dt_clf, data, label, scoring='accuracy',cv=5, return_train_score=True)

In [6]:
crs

{'fit_time': array([0.00099969, 0.00199151, 0.        , 0.0010016 , 0.00100183]),
 'score_time': array([0.00100708, 0.        , 0.0009973 , 0.        , 0.        ]),
 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [7]:
import pandas as pd
pd.DataFrame(crs)

fit_time  score_time  test_score  train_score
0  0.001000    0.001007    0.966667          1.0
1  0.001992    0.000000    0.966667          1.0
2  0.000000    0.000997    0.900000          1.0
3  0.001002    0.000000    0.966667          1.0
4  0.001002    0.000000    1.000000          1.0

In [16]:
scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

## confusion matrix 
- 정확도, 정밀도, 재현율, f1스코어, auc, roc커브 등등 

In [17]:
scores = cross_val_score(dt_clf, data, label, scoring='precision',cv=5)

/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 136, in __call__
    score = scorer._score(
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 2127, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", lin

In [19]:
scores = cross_val_score(dt_clf, data, label, scoring='f1',cv=5)

/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 136, in __call__
    score = scorer._score(
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1238, in f1_score
    return fbeta_score(
  File "/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 184, in wrapper
    return func

In [20]:
scores

array([nan, nan, nan, nan, nan])

- 이진분류와
- 이진분류는 0,1 나눠져 있다.
- 흔히 말하는 계산방식 정확도, 정밀도, 재현율, f1스코어, auc, roc커브 등등  0,1 이진 분류에만 디폴트로 적용된 것 
- 이진분류는 문제 없이 값들이 나온다.
- 이진분류는 0,1 가정하에서 디포릍로 정밀도, 재현율, f1스코어 등등이 나온다.

- 다중분류에는
- 0,1,2 이다.


- 값을 평가하는 방식이 다릅니다.

## 다중분류 진행시 정확도 외 다른 평가지표에 대한 가중치 설정 방법
- 다중분류시 평가지표를 확인하기 위해서는 _micro, _macro, _weighted 이런 식으로 사용하면 된다.

- macro
- 모든 예측 결과에 대해서 평균을 내어서 값을 계산하는 방법 
- micro
- 각각의 정답에 대한 개수를 가지고 나눠서 평균값을 구한다.
- weighted
- 가중 평균값을 구한다. 가중치를 주고 싶은 것에 줄 수 있다.

In [38]:
scores = cross_val_score(dt_clf, data, label, scoring='precision_micro',cv=5)

In [39]:
scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

- 하나의 예로 
- 4개의 라벨 
- 0,1,2,3 클래스있을 것
- precision 값을 계산해보니 
- 0 0.5 = 1/2
- 1 0.1 = 10/100
- 2 0.5 = 1/2
- 3 0.5 = 1/2

- macro : (0.5+0.1+0.5+0.5)/4

- micro로 계산하는 방식은?
- (1+10+1+1)/(2+100+2+2)

- macro, micro 사용할 때 나올 수 있는 평가지표 값은 다르다.
- 잘 알고 계셔야 한다.
- 클래스에 대한 불균형에 따라서 두 개의 값을 다르게 사용해야 한다.
- 대부분 둘 다 사용하고 두 지표 보여주면서 이렇게 나왔습니다 넘어가는 경우가 많다.



## 이 두 가지를 언제 사용해야 하는가?
## 둘의 차이는 무엇인가?
###  클래스 불균형일 때 영향도를 생각해서 사용하면 된다.

- 2,100,2,2 206개의 클래스에서
- 만약 데이터를 랜덤하게 뽑는다고 한다면 
- 확률적으로 우리가 클래스를 뽑을 확률은 1높다.

- 사기탐지 같은 것 보면
- 대부분 정상인데 사기인경우가 적다
- 대부분의 데이터는 정상
- 사기가 한 두 개 나오는 경우


### 필수과제 1
- weighted 구글링하셔서
- 내용설명과 실제 코드 작성해서 
- 값에 대한 비교 정리하기


In [40]:
(0.5+0.1+0.5+0.5)/4

0.4

In [41]:
(1+10+1+1)/(2+100+2+2)

0.12264150943396226

In [23]:
import seaborn as sns
df =sns.load_dataset('titanic')

In [26]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class   
0           0       3    male  22.0      1      0   7.2500        S   Third  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [31]:
df_tt=df[['pclass','fare']]

In [32]:
scores = cross_val_score(dt_clf, df_tt, df['survived'], scoring='accuracy',cv=5)
print(np.round(np.mean(scores),3))

0.688


In [33]:
scores

array([0.62569832, 0.66853933, 0.68539326, 0.73033708, 0.73033708])

In [34]:
scores = cross_val_score(dt_clf, df_tt, df['survived'], scoring='f1',cv=5)

In [35]:
scores

array([0.42735043, 0.4957265 , 0.53333333, 0.60655738, 0.61290323])

In [36]:
scores = cross_val_score(dt_clf, df_tt, df['survived'], scoring='precision',cv=5)

In [37]:
scores

array([0.52083333, 0.59183673, 0.61538462, 0.68518519, 0.69090909])

## leaveOneOut 교차검증 
## Group교차검증

- 그룹핑은 그룹핑 데이터를 가지고 교차검증할 때 더 좋은 성능을 보여줄 수 있다.
- 단순하게 교차검증을 cross 하는 게 아니라
- 데이터의 특성을 보고 내가 분석  할 것이 어떤 클래스별의 수치를 비교하는 것이라면 교차검증 자체도 그룹핑으로 접근할 수 있는 것

In [49]:
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()

In [51]:
scores =cross_val_score(dt_clf, df_tt, df['survived'], scoring='accuracy',cv=loo)

In [52]:
print(len(scores))
print(scores.mean())

891
0.6745230078563412


In [ ]:
## cross val 응용하기 
model = [DecisionTreeClassifier(),RandomForestClassifier(),LogisticRegression()] 
name = ['DT','RF','LR']

for model ,name in zip(model, name):
    print('******************사용한 알고리즘',name,'******************')
    for score in ['accuracy','precision','recall','f1']:
        print(score)
        print('--')
        print(cross_val_score(model, df_tt, df['survived'], scoring=score,cv=10))

### 필수과제2
- 추가로 1개 또느 2개 이하로 다른 교차검증 패키지 사용해 보기
- 개념설명과 실제 적용해서 나온 결과 값을 비교하기
- e.g) 타이타닉 데이터로 한다면 기존에 교차검증과 새롭게 진행한 교차검증의 차이를 비교해 주세요!

# 평가지표 

- 분류
- 회귀

- 둘 다 다르게 측정한다
- 딥러닝은 비용함수 

- 우리는 ML에대해서 분류와 회귀로 평가지표 확인하기!

### 분류
- 정확도, 정밀도, 재현율, f1, roc 
- 구성요소가 어떤 식으로 되어 있는 것이고
- 정밀도, 재현율의 차이가 어떤 상황에 맞는 것이고
- 왜 우리는 그래서 f1스코어를 보는지?
- roc커브에 x축과 y축이 의미하는 것은?


## 정확도
- Accuracy = 예측의 결과(0,1) 동일한 데이터 건수 /전체 예측 데이터 건수

- 맞춘다는 것이 1만 맞춘다는 것으로 생각하지만- >0도 맞춘 것
- 0과 1을 둘 다 맞춘 것을 고민을 해야 한다.


- 정밀도, 재현율 등을 이해하려면 오차행렬 confusion matrix를 이해해야 함

### 2진분류가 디폴트
### 0,1 에 대한 기준은 다르게 설정할 수 있다. ( 1이 성공이 아니라 1이 실패로 설정할 수 있음) 
### 클래스에 대한 기준에 따라 매트릭스 결과도 다르게 볼 수 있다.
### 기본적으로 0보다는 1을 예측을 하려고 하니깐 
            - 예측값
            0(negative)                1(positive)
       0   TN(True Negative)           FP(False Positive)
- 실제값

      1    FN(False Negative)          TP(True Postivie)
      
      
- 앞에는 대부분 True, False 참 또는 거짓
- 참과 거짓을 선별하는 기준은 실제값과 예측값이 같냐 틀리냐에 따라 다르다.
- Neg, pos 예측한 값에 대한 라벨링을 말하는 것

- 0,1,2

- 0, (1,2)
- 1, (0,2)

### 전시간에 냈던 과제도 다 노션에 업로드 잘 부탁드립니다!